# Generated by Django 6.0.3 on 2026-03-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('incidence_rate', models.DecimalField(decimal_places=2, help_text='Cases per 100k', max_digits=6)),
                ('age_group', models.CharField(default='All ages', max_length=50)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Melbourne', max_length=100)),
                ('state', models.CharField(default='Victoria', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_uv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_uv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('label', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
            ],
            options={
                'ordering': ['min_uv'],
            },
        ),
        migrations.CreateModel(
            name='UVReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uv_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('risk_level', models.CharField(max_length=20)),
                ('observation_time', models.DateTimeField()),
                ('burn_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uv_readings', to='core.location')),
            ],
            options={
                'ordering': ['-observation_time'],
            },
        ),
    ]
