# Generated by Django 6.0.3 on 2026-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cancerstatistic_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelanomaMortalityStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('mortality_rate', models.DecimalField(decimal_places=2, help_text='Deaths per 100k', max_digits=6)),
                ('age_group', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
